use crate::app::{ActivityEntry, SessionRecord, SessionState, TimelineEntry, TimelineKind};

pub fn sessions() -> Vec<SessionRecord> {
    vec![
        SessionRecord {
            id: "sess-gateway-001".to_owned(),
            title: "Gateway routing soak".to_owned(),
            origin: "Local".to_owned(),
            modified: "9h ago".to_owned(),
            created: "16h ago".to_owned(),
            channel: "control".to_owned(),
            actor: None,
            thread: None,
            route: "gateway.default".to_owned(),
            runtime: "primary-agent".to_owned(),
            model: "gpt-5.4-control".to_owned(),
            state: SessionState::Active,
            unread: 2,
            draft: String::new(),
            transcript_len: 0,
            current_run_id: None,
            current_gateway_run_id: None,
            last_gateway_run_id: None,
            memory_summary: Some(
                "Gateway routing soak and local control attachment state.".to_owned(),
            ),
            compressed_context: Some(
                "Earlier turns covered route health checks and mock gateway transport stability."
                    .to_owned(),
            ),
            references: vec!["sess-node-007 (node follow-up)".to_owned()],
            streaming_preview: None,
            streaming_run_id: None,
            active_turn: None,
            timeline: vec![
                entry(
                    "15:02",
                    TimelineKind::System,
                    "gateway",
                    "Session attached",
                    "Operator console attached to gateway.default with mock transport.",
                ),
                entry(
                    "15:03",
                    TimelineKind::Agent,
                    "pi",
                    "Thinking",
                    "Evaluating route health, node pressure, and whether the gateway is stable enough to continue.",
                ),
                entry(
                    "15:04",
                    TimelineKind::Tool,
                    "exec",
                    "Working",
                    "Preparing the next control-plane action while waiting for real gateway execution wiring.",
                ),
            ],
        },
        SessionRecord {
            id: "sess-ops-013".to_owned(),
            title: "Launch readiness audit".to_owned(),
            origin: "Remote".to_owned(),
            modified: "1d ago".to_owned(),
            created: "1d ago".to_owned(),
            channel: "slack".to_owned(),
            actor: Some("release-ops".to_owned()),
            thread: Some("launch-readiness".to_owned()),
            route: "ops.launch".to_owned(),
            runtime: "sub-agent:release".to_owned(),
            model: "gpt-5.4-mini".to_owned(),
            state: SessionState::Waiting,
            unread: 1,
            draft: String::new(),
            transcript_len: 0,
            current_run_id: None,
            current_gateway_run_id: None,
            last_gateway_run_id: None,
            memory_summary: Some(
                "Release checklist request and draft rollout checkpoints.".to_owned(),
            ),
            compressed_context: None,
            references: vec![],
            streaming_preview: None,
            streaming_run_id: None,
            active_turn: None,
            timeline: vec![
                entry(
                    "14:51",
                    TimelineKind::Operator,
                    "operator",
                    "Requested deployment checklist",
                    "Need a compact checkpoint list before opening the release window.",
                ),
                entry(
                    "14:54",
                    TimelineKind::Agent,
                    "release-agent",
                    "Checklist draft",
                    "Drafted rollout, rollback, and observability checkpoints for the cluster.",
                ),
                entry(
                    "14:58",
                    TimelineKind::System,
                    "gateway",
                    "Awaiting operator input",
                    "Session is idle and ready for the next routing or execution command.",
                ),
            ],
        },
        SessionRecord {
            id: "sess-node-007".to_owned(),
            title: "iOS node attach".to_owned(),
            origin: "Remote".to_owned(),
            modified: "2d ago".to_owned(),
            created: "2d ago".to_owned(),
            channel: "telegram".to_owned(),
            actor: Some("ios-primary".to_owned()),
            thread: None,
            route: "device.ios.primary".to_owned(),
            runtime: "node-supervisor".to_owned(),
            model: "gpt-5.4-control".to_owned(),
            state: SessionState::Degraded,
            unread: 0,
            draft: String::new(),
            transcript_len: 0,
            current_run_id: None,
            current_gateway_run_id: None,
            last_gateway_run_id: None,
            memory_summary: Some(
                "Node reconnect flow is degraded and awaiting reattach.".to_owned(),
            ),
            compressed_context: None,
            references: vec![],
            streaming_preview: None,
            streaming_run_id: None,
            active_turn: None,
            timeline: vec![
                entry(
                    "14:24",
                    TimelineKind::System,
                    "gateway",
                    "Node reconnect required",
                    "Last heartbeat exceeded the threshold. Control plane marked the node degraded.",
                ),
                entry(
                    "14:26",
                    TimelineKind::Agent,
                    "node-supervisor",
                    "Recovery stub",
                    "Future device reattach commands and logs will replace this placeholder flow.",
                ),
            ],
        },
        SessionRecord {
            id: "sess-web-021".to_owned(),
            title: "Webchat intake drift".to_owned(),
            origin: "Remote".to_owned(),
            modified: "4d ago".to_owned(),
            created: "4d ago".to_owned(),
            channel: "webchat".to_owned(),
            actor: Some("guest-102".to_owned()),
            thread: Some("checkout-drift".to_owned()),
            route: "support.web.intake".to_owned(),
            runtime: "triage-agent".to_owned(),
            model: "gpt-5.4-mini".to_owned(),
            state: SessionState::Waiting,
            unread: 0,
            draft: String::new(),
            transcript_len: 0,
            current_run_id: None,
            current_gateway_run_id: None,
            last_gateway_run_id: None,
            memory_summary: Some("Webchat intake route pending operator policy update.".to_owned()),
            compressed_context: None,
            references: vec![],
            streaming_preview: None,
            streaming_run_id: None,
            active_turn: None,
            timeline: vec![entry(
                "13:02",
                TimelineKind::System,
                "gateway",
                "Awaiting route policy update",
                "Mock webchat intake session is idle until the next operator command arrives.",
            )],
        },
        SessionRecord {
            id: "sess-mac-032".to_owned(),
            title: "macOS node prep".to_owned(),
            origin: "Local".to_owned(),
            modified: "4d ago".to_owned(),
            created: "4d ago".to_owned(),
            channel: "control".to_owned(),
            actor: None,
            thread: None,
            route: "device.macos.lab".to_owned(),
            runtime: "node-supervisor".to_owned(),
            model: "gpt-5.4-control".to_owned(),
            state: SessionState::Waiting,
            unread: 0,
            draft: String::new(),
            transcript_len: 0,
            current_run_id: None,
            current_gateway_run_id: None,
            last_gateway_run_id: None,
            memory_summary: Some("macOS node is waiting on device capability grant.".to_owned()),
            compressed_context: None,
            references: vec![],
            streaming_preview: None,
            streaming_run_id: None,
            active_turn: None,
            timeline: vec![entry(
                "11:48",
                TimelineKind::Agent,
                "node-supervisor",
                "Pending device grant",
                "Device capability approval remains mock-only until real node integration lands.",
            )],
        },
    ]
}

pub fn activity_feed() -> Vec<ActivityEntry> {
    vec![
        ActivityEntry {
            timestamp: "15:05".to_owned(),
            scope: "gateway".to_owned(),
            message: "Mock websocket connected to local control-plane bridge.".to_owned(),
        },
        ActivityEntry {
            timestamp: "15:05".to_owned(),
            scope: "runtime".to_owned(),
            message: "Primary runtime heartbeat steady; event bus integration pending.".to_owned(),
        },
        ActivityEntry {
            timestamp: "15:06".to_owned(),
            scope: "tools".to_owned(),
            message: "Execution panel is scaffolded for tool stdout, results, and failures."
                .to_owned(),
        },
        ActivityEntry {
            timestamp: "15:06".to_owned(),
            scope: "nodes".to_owned(),
            message: "Device-node stream is placeholder-only in stage 1.".to_owned(),
        },
        ActivityEntry {
            timestamp: "15:07".to_owned(),
            scope: "command".to_owned(),
            message: "Use /help in the composer for local control commands.".to_owned(),
        },
        ActivityEntry {
            timestamp: "15:08".to_owned(),
            scope: "session".to_owned(),
            message: "Press r to open the session resume browser.".to_owned(),
        },
    ]
}

fn entry(
    timestamp: &str,
    kind: TimelineKind,
    actor: &str,
    title: &str,
    body: &str,
) -> TimelineEntry {
    TimelineEntry {
        timestamp: timestamp.to_owned(),
        kind,
        block: kind.default_block(),
        actor: actor.to_owned(),
        title: title.to_owned(),
        body: body.to_owned(),
        run_id: None,
        phase: None,
        details: Vec::new(),
        details_expanded: false,
    }
}
