use super::*;

pub fn load_from_file(path: impl AsRef<Path>) -> Result<AppConfig> {
    let content = fs::read_to_string(path)?;
    let cfg = serde_yaml::from_str::<AppConfig>(&content)?;
    Ok(cfg)
}

pub fn load_extension_manifest_from_file(path: impl AsRef<Path>) -> Result<ExtensionManifest> {
    let content = fs::read_to_string(path)?;
    let cfg = serde_yaml::from_str::<ExtensionManifest>(&content)?;
    Ok(cfg)
}

pub fn default_workspace_config_path(cwd: impl AsRef<Path>) -> PathBuf {
    cwd.as_ref().join(".mosaic").join("config.yaml")
}

pub fn default_user_config_path() -> Option<PathBuf> {
    let home = env::var_os("HOME")?;
    Some(PathBuf::from(home).join(".config/mosaic/config.yaml"))
}

pub fn default_config_template() -> Result<String> {
    let body = serde_yaml::to_string(&MosaicConfig::default())?;
    Ok(format!(
        "# Mosaic workspace configuration\n# Generated by `mosaic setup init`.\n\n{body}"
    ))
}

pub fn save_mosaic_config(path: impl AsRef<Path>, config: &MosaicConfig) -> Result<()> {
    let path = path.as_ref();

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let body = serde_yaml::to_string(config)?;
    fs::write(path, body)?;
    Ok(())
}

pub fn init_workspace_config(cwd: impl AsRef<Path>, force: bool) -> Result<PathBuf> {
    let cwd = cwd.as_ref();
    let path = default_workspace_config_path(cwd);

    if path.exists() && !force {
        bail!(
            "workspace config already exists at {} (pass --force to overwrite)",
            path.display()
        );
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    let config = MosaicConfig::default();
    save_mosaic_config(&path, &config)?;
    fs::create_dir_all(cwd.join(&config.session_store.root_dir))?;
    fs::create_dir_all(cwd.join(&config.inspect.runs_dir))?;
    fs::create_dir_all(cwd.join(&config.audit.root_dir))?;
    fs::create_dir_all(cwd.join(".mosaic/extensions"))?;

    Ok(path)
}

pub fn load_mosaic_config(options: &LoadConfigOptions) -> Result<LoadedMosaicConfig> {
    let mut config = MosaicConfig::default();
    let mut sources = vec![ConfigSource {
        kind: ConfigSourceKind::Defaults,
        detail: "built-in defaults".to_owned(),
    }];

    let user_config_path = options
        .user_config_path
        .clone()
        .or_else(default_user_config_path);
    if let Some(user_path) = user_config_path.as_ref().filter(|path| path.exists()) {
        let patch = load_config_patch(user_path)?;
        merge_patch(&mut config, patch);
        sources.push(ConfigSource {
            kind: ConfigSourceKind::User,
            detail: user_path.display().to_string(),
        });
    }

    let workspace_config_path = options
        .workspace_config_path
        .clone()
        .unwrap_or_else(|| default_workspace_config_path(&options.cwd));
    if workspace_config_path.exists() {
        let patch = load_config_patch(&workspace_config_path)?;
        merge_patch(&mut config, patch);
        sources.push(ConfigSource {
            kind: ConfigSourceKind::Workspace,
            detail: workspace_config_path.display().to_string(),
        });
    }

    if let Ok(active_profile) = env::var(ACTIVE_PROFILE_ENV) {
        if !active_profile.trim().is_empty() {
            config.active_profile = active_profile;
            sources.push(ConfigSource {
                kind: ConfigSourceKind::Env,
                detail: ACTIVE_PROFILE_ENV.to_owned(),
            });
        }
    }

    if let Some(active_profile) = options.overrides.active_profile.clone() {
        config.active_profile = active_profile;
        sources.push(ConfigSource {
            kind: ConfigSourceKind::Cli,
            detail: "active profile override".to_owned(),
        });
    }

    Ok(LoadedMosaicConfig {
        config,
        sources,
        workspace_config_path,
        user_config_path,
    })
}

pub(crate) fn load_config_patch(path: &Path) -> Result<MosaicConfigPatch> {
    let content = fs::read_to_string(path)
        .with_context(|| format!("failed to read config layer {}", path.display()))?;
    let patch = serde_yaml::from_str::<MosaicConfigPatch>(&content)
        .with_context(|| format!("failed to parse config layer {}", path.display()))?;
    Ok(patch)
}

pub(crate) fn merge_patch(config: &mut MosaicConfig, patch: MosaicConfigPatch) {
    if let Some(schema_version) = patch.schema_version {
        config.schema_version = schema_version;
    }

    if let Some(active_profile) = patch.active_profile {
        config.active_profile = active_profile;
    }

    if !patch.profiles.is_empty() {
        config.profiles.extend(patch.profiles);
    }

    if let Some(deployment) = patch.deployment {
        config.deployment = deployment;
    }

    if let Some(auth) = patch.auth {
        config.auth = auth;
    }

    if let Some(session_store) = patch.session_store {
        config.session_store = session_store;
    }

    if let Some(inspect) = patch.inspect {
        config.inspect = inspect;
    }

    if let Some(audit) = patch.audit {
        config.audit = audit;
    }

    if let Some(observability) = patch.observability {
        config.observability = observability;
    }

    if let Some(extensions) = patch.extensions {
        config.extensions = extensions;
    }

    if let Some(policies) = patch.policies {
        config.policies = policies;
    }
}
