#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT_DIR/.." && pwd)"
cd "$ROOT_DIR"

if ! command -v cargo >/dev/null 2>&1; then
  echo "error: cargo not found in PATH" >&2
  exit 1
fi

TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/mosaic-regression-XXXXXX")"
TMP_TESTS="$TMP_ROOT/tests.txt"
TMP_DOCS="$TMP_ROOT/docs.txt"
OUT_FILE="$ROOT_DIR/docs/regression-catalog.md"

cleanup() {
  rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

cargo test --workspace -- --list >"$TMP_TESTS" 2>&1
find "$ROOT_DIR/docs" -maxdepth 1 -type f -name "*.md" | sort >"$TMP_DOCS"
if [[ -f "$PROJECT_ROOT/WORKLOG.md" ]]; then
  echo "$PROJECT_ROOT/WORKLOG.md" >>"$TMP_DOCS"
fi
sort -u -o "$TMP_DOCS" "$TMP_DOCS"

TEST_COUNT="$(
  awk '
    /: test$/ { count++ }
    END { print count + 0 }
  ' "$TMP_TESTS"
)"
DOC_COUNT="$(wc -l <"$TMP_DOCS" | tr -d ' ')"
GENERATED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

{
  echo "# Regression Catalog"
  echo
  echo "This file is generated by \`scripts/update_regression_catalog.sh\`."
  echo
  echo "- Generated at (UTC): \`$GENERATED_AT\`"
  echo "- Total test cases: \`$TEST_COUNT\`"
  echo "- Total docs: \`$DOC_COUNT\`"
  echo
  echo "## Documentation Inventory"
  echo
  while IFS= read -r doc_path; do
    if [[ "$doc_path" == "$ROOT_DIR/"* ]]; then
      rel_path="${doc_path#$ROOT_DIR/}"
    elif [[ "$doc_path" == "$PROJECT_ROOT/"* ]]; then
      rel_path="${doc_path#$PROJECT_ROOT/}"
    else
      rel_path="$doc_path"
    fi
    echo "- \`$rel_path\`"
  done <"$TMP_DOCS"
  echo
  echo "## Test Case Inventory"
  echo
  awk '
    /^[[:space:]]*Running / {
      suite = $0
      sub(/^[[:space:]]*Running /, "", suite)
      current_suite = suite
      if (!(suite in seen_suite)) {
        order[++suite_count] = suite
        seen_suite[suite] = 1
      }
      next
    }
    /: test$/ {
      test_name = $0
      sub(/: test$/, "", test_name)
      tests[current_suite] = tests[current_suite] "- `" test_name "`\n"
      suite_tests[current_suite]++
      next
    }
    END {
      for (i = 1; i <= suite_count; i++) {
        suite = order[i]
        count = suite_tests[suite] + 0
        if (count == 0) {
          continue
        }
        printf "### %s\n\n", suite
        printf "_Cases: %d_\n\n", count
        printf "%s\n", tests[suite]
      }
    }
  ' "$TMP_TESTS"
  echo
  echo "## Regenerate"
  echo
  echo '```bash'
  echo "cd cli"
  echo "./scripts/update_regression_catalog.sh"
  echo '```'
} >"$OUT_FILE"

echo "updated: $OUT_FILE"
